sm8450-common: DeviceSettings: Define used libraries
* Trigger build error in A14 build system

error: mismatch in the <uses-library> tags between the build system and the manifest:
  - required libraries in build system: []
                   vs. in the manifest: []
  - optional libraries in build system: []
                   vs. in the manifest: [androidx.window.extensions, androidx.window.sidecar]
  - tags in the manifest (out/target/common/obj/APPS/DeviceSettings_intermediates/manifest/AndroidManifest.xml)

Signed-off-by: Pranav Vashi <neobuddy89@gmail.com>